name: CI/CD — Build and Deploy to App Engine

on:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Export secrets into build env
        run: |
          echo "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}" >> $GITHUB_ENV
          echo "CLERK_SECRET_KEY=${{ secrets.CLERK_SECRET_KEY }}" >> $GITHUB_ENV
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> $GITHUB_ENV
          echo "VERTEX_AI_PROJECT=${{ secrets.VERTEX_AI_PROJECT }}" >> $GITHUB_ENV
          echo "VERTEX_AI_LOCATION=${{ secrets.VERTEX_AI_LOCATION }}" >> $GITHUB_ENV

      - name: Build app
        run: npm run build
        env:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          VERTEX_AI_PROJECT: ${{ secrets.VERTEX_AI_PROJECT }}
          VERTEX_AI_LOCATION: ${{ secrets.VERTEX_AI_LOCATION }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: neural-land-469712-t7
          export_default_credentials: true


      - name: Submit Cloud Build (build + deploy + monitoring)
        run: |
          gcloud builds submit --config cloudbuild.yaml --project=neural-land-469712-t7 .